### ISSUE TITLE
Apply the logic to the custom cards [main view]

### ISSUE THREAD

**Issue by buseca** [dbertella/relist#15]
In the main view of the app,
the cards of the items need to be composed according to the logics specified in the 'metadata' sheet.

Schema of the logics to consider: https://www.figma.com/file/hhdz2ocXDDqKrPzv4x2v7o/Cauldron-list?type=design&node-id=607%3A7206&mode=design&t=CwDPR3FZRxDXHkPy-1

Note: some logics impact the position of the data, some impact the visibility, and some other impact only the style, so different solutions are possible.

**Comment by buseca** [comment]
@dbertella components are rendered when there is no data:


Texts
![Image](https://github.com/dbertella/relist/assets/3997836/fc122980-7580-449d-99cf-cba0387ac080)

Tags
![Image](https://github.com/dbertella/relist/assets/3997836/6a24633a-836b-4e42-92a6-3d487dcb1a3f)

Images
![Image](https://github.com/dbertella/relist/assets/3997836/ee53b8a7-9421-4b90-b8cd-e4a8befcdbe5)

Numbers
![Image](https://github.com/dbertella/relist/assets/3997836/1a4a468b-ddd6-4211-94d6-900f4bb73823)

Numbers innercard
![Image](https://github.com/dbertella/relist/assets/3997836/f7ff40b9-6bb3-4450-8fe0-75f6d504d517)

Titles
![Image](https://github.com/dbertella/relist/assets/3997836/2aa089b7-9352-464a-8b1e-766fce2f3979)

**Comment by dbertella** [comment]
Doesn't make sense to make some of those fields required? If you are missing those data filters won't work for example. How come you don't have a title for a card? Anyway we can render them conditionally, but maybe we should think how to make some of them required

**Comment by buseca** [comment]
@dbertella As long as it doesn't make it too complex, let's try not setting constraints for now. The risk is to decrease the flexibility, and we want to cover as many unknown use cases we can.
The only requirement is that an item should have at least 1 field set in order to be rendered.

**Comment by dbertella** [comment]
I pushed some changes on this, feel free to close once you are happy with it or let me know otherwise

**Comment by buseca** [comment]
many are solved but we still have the inner card rendered empty:

![Image](https://github.com/dbertella/relist/assets/3997836/75cf8734-c064-4d1f-9366-601c733a66b4)

**Comment by dbertella** [comment]
Going to close this, feel free to open a new issue in case you see some more problems
